### ISSUE TITLE
Disable shallow clone

### ISSUE THREAD

**Issue by redcatbear** [exasol/exasol-testcontainers#148]
## Situation

Sonar cloud issues the following warning with the analysis:

> Shallow clone detected during the analysis. Some files will miss SCM information. This will affect features like auto-assignment of issues. Please configure your build to disable shallow clone.

## Solution

Add `fetch-depth: 0` to your GHA workflow:

```
steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
```

## Acceptance Criteria

* SonarCloud warning about shallow clone fixed.
